# Generated by Django 5.0.6 on 2024-08-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRecord',
            new_name='AcesssRecords',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='email',
        ),
    ]
